# Generated by Django 3.2.16 on 2022-10-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('rating', models.FloatField()),
                ('updated_at', models.DateField(null=True)),
            ],
        ),
    ]
